services:
  kakusin-api:
    container_name: kakusin-api
    build:
      # Sửa lại đường dẫn build trỏ vào bên trong thư mục api
      context: './api/docker/8.5'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '1000'
    image: 'kakusin-api-image'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8000:80'
      - '5173:5173'
    # Gọi file .env của Laravel để nạp biến môi trường
    env_file:
      - ./api/.env
    environment:
      WWWUSER: '1000'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: 'client_host=host.docker.internal'
      IGNITION_LOCAL_SITES_PATH: '${PWD}/api'
    volumes:
      # Map thư mục api vào /var/www/html trong container
      - './api:/var/www/html'
      
      # --- TỐI ƯU 1: TRÁNH NGHẼN ĐỒNG BỘ THƯ MỤC RÁC CHO WINDOWS (Học từ cty bro) ---
      - /var/www/html/vendor
      - /var/www/html/node_modules
      # -------------------------------------------------------------
    networks:
      - kakusin-net
    depends_on:
      - kakusin-mysql

  kakusin-mysql:
    container_name: kakusin-mysql
    image: 'mysql:8.0' # Dùng bản 8.0 cho ổn định giống cty bro
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kakusin_db
      MYSQL_USER: kakusin
      MYSQL_PASSWORD: password
    volumes:
      - 'kakusin-mysql-data:/var/lib/mysql'
    networks:
      - kakusin-net

  kakusin-wordpress:
    container_name: kakusin-wordpress
    image: wordpress:latest
    environment:
      - WORDPRESS_DB_HOST=kakusin-mysql:3306
      - WORDPRESS_DB_USER=kakusin
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=kakusin_db
    ports:
      - '8080:80'
    volumes:
      - ./cms:/var/www/html
    depends_on:
      - kakusin-mysql
    networks:
      - kakusin-net

networks:
  kakusin-net:
    driver: bridge

volumes:
  kakusin-mysql-data:
    driver: local